backend:
  name: git-gateway
  branch: main

# Configuration pour développement local (optionnel)
# local_backend: true

media_folder: "Assets/uploads"
public_folder: "/Assets/uploads"

site_url: https://projectnumina-website.netlify.app
display_url: https://projectnumina-website.netlify.app

collections:
  # Collection pour les membres de la communauté
  - name: "communaute"
    label: "Communauté"
    folder: "data/team"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Avatar", name: "image", widget: "image", required: false}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "select", multiple: true, options: ["Active Contributor", "Alumni", "Founding Members", "Scientific Advisors"]}

  # Collection pour les projets
  - name: "projets"
    label: "Projets"
    folder: "data/projects"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "URL", name: "url", widget: "string", required: false}
      - {label: "GitHub", name: "github", widget: "string", required: false}

  # Collection pour les articles de blog
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Statut", name: "status", widget: "select", options: ["publié", "brouillon"], default: "brouillon"}
      - {label: "CTAs", name: "ctas", widget: "list", required: false, fields: [
          {label: "Texte", name: "text", widget: "string"},
          {label: "URL", name: "url", widget: "string"},
          {label: "Type", name: "type", widget: "select", options: ["primary", "secondary"], default: "primary"}
        ]}

  # Collection pour les pages principales (optionnel)
  - name: "parametres"
    label: "Paramètres"
    files:
      - file: "data/site-settings.json"
        label: "Paramètres du site"
        name: "site-settings"
        fields:
          - {label: "Nom du site", name: "site_name", widget: "string"}
          - {label: "Description", name: "description", widget: "text"} 